CREATE TABLE orders (
  id SERIAL PRIMARY KEY,
  user_id  INTEGER NOT NULL REFERENCES users (id),
  status  VARCHAR(20) DEFAULT 'active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);