CREATE TABLE order_products (
  id SERIAL PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products (id),
  quantity  INTEGER NOT NULL DEFAULT '1',
  order_id   INTEGER NOT NULL REFERENCES orders (id),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);